# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app/backend
RUN pip install --upgrade pip
# Install any needed packages specified in requirements.txt
RUN pip install -r backend/requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME World

# Run flask_app.py when the container launches
#CMD ["gunicorn", "-k", "eventlet", "-w", "1", "backend.app:app", "--bind", "0.0.0.0:5000"]