version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ./backend :/app/backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
#    ports:
#        - "$JUPYTER_PORT:$JUPYTER_PORT"
#        - "$TENSORBOARD_PORT:$TENSORBOARD_PORT"
#    env_file:
#     - ./.env
    entrypoint: gunicorn -k eventlet -w 1 backend.app:app --bind 0.0.0.0:5000
